### ISSUE TITLE
A crash again

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#155] opened 2017-03-14 18:06 UTC
MaxBook:MKHRequirement maxim$ xcake make
  - Reading Cakefile
  - Creating Project
  - Creating Target<>
  - Creating Target<Tst>
  - Creating Target<MKHRequirement>
  - Resolving Project
  - Resolving Target<>
  - Resolving Target<Tst>
  - Resolving Target<MKHRequirement>
  - Creating build configurations for Project<Main>
  - Creating build configuration Debug for Project<Main>
  - Creating build configuration Release for Project<Main>
  - Creating build configurations for Target<>
  - Creating build configuration Debug for Target<>
  - Creating build configuration Release for Target<>
  - Creating build configurations for Target<Tst>
  - Creating build configuration Debug for Target<Tst>
  - Creating build configuration Release for Target<Tst>
  - Creating build configurations for Target<MKHRequirement>
  - Creating build configuration Debug for Target<MKHRequirement>
  - Creating build configuration Release for Target<MKHRequirement>
  - Creating User Schemes
/Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/generator/scheme_generator.rb:33:in `block in visit_target': undefined method `build_for_running' for #<Xcodeproj::XCScheme::BuildAction:0x007fde710aba70> (NoMethodError)
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/generator/scheme_generator.rb:16:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/generator/scheme_generator.rb:16:in `visit_target'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/visitor.rb:45:in `visit'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `accept'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/command/make.rb:25:in `block in run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.8/bin/xcake:6:in `<top (required)>'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/xcake:22:in `load'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/xcake:22:in `<main>'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'

**Comment by maximkhatskevich** [comment] 2017-03-14 18:07
Any ideas why?

**Comment by maximkhatskevich** [comment] 2017-03-14 18:07
Sometimes the output is like this:

MaxBook:MKHRequirement maxim$ xcake make
  - Reading Cakefile
  - Creating Project
  - Creating Target<>
  - Creating Target<Tst>
  - Creating Target<MKHRequirement>
  - Resolving Project
  - Resolving Target<>
  - Resolving Target<Tst>
  - Resolving Target<MKHRequirement>
  - Creating build configurations for Project<Main>
  - Creating build configuration Debug for Project<Main>
  - Creating build configuration Release for Project<Main>
  - Creating build configurations for Target<>
  - Creating build configuration Debug for Target<>
  - Creating build configuration Release for Target<>
  - Creating build configurations for Target<Tst>
  - Creating build configuration Debug for Target<Tst>
  - Creating build configuration Release for Target<Tst>
  - Creating build configurations for Target<MKHRequirement>
  - Creating build configuration Debug for Target<MKHRequirement>
  - Creating build configuration Release for Target<MKHRequirement>
Platform not supported!

**Comment by jcampbell05** [comment] 2017-03-14 19:09
@maximkhatskevich I think this is the same crash as before, if you clone this repo and run `rake install` then the development version of `0.8.9` should be installed and you can see if that fixes it.

I'm considering releasing 0.8.9 with these fixes and doing another 0.8.10 with the rest

**Comment by maximkhatskevich** [comment] 2017-03-14 19:20
I think iterating faster would be better than waiting for longer :) Okay, I'll try to install from sources, but a release would be very welcome!

**Comment by jcampbell05** [comment] 2017-03-14 19:20
@maximkhatskevich sure I'll release tonight :)

**Comment by maximkhatskevich** [comment] 2017-03-14 19:26
Should I use 'master' branch for installing from source?

**Comment by maximkhatskevich** [comment] 2017-03-14 19:43
MaxBook:xcake maxim$ rake install
rake aborted!
LoadError: cannot load such file -- bundler/gem_tasks
/Users/maxim/Dev/xcake/Rakefile:1:in `<top (required)>'
/Users/maxim/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/maxim/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/maxim/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by maximkhatskevich** [comment] 2017-03-14 19:46
doesn't work, even if I switch to ruby 2.0.0

**Comment by jcampbell05** [comment] 2017-03-14 19:47
ah you need to run `gem install rake && gem install bundle` and then re run it :)

**Comment by maximkhatskevich** [comment] 2017-03-14 19:49
omg... I'm almost ready to give up on all that Ruby stuff... :) Okay, doing that now.

**Comment by jcampbell05** [comment] 2017-03-14 19:52
@maximkhatskevich  haha it's a learning curve at first but then you get used to it haha

**Comment by maximkhatskevich** [comment] 2017-03-14 19:53
Anyway...

MaxBook:xcake maxim$ rake install
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/Users/maxim/Dev/xcake/Rakefile:2:in `<top (required)>'
/Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
/Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by maximkhatskevich** [comment] 2017-03-14 19:53
after installing the above

**Comment by maximkhatskevich** [comment] 2017-03-14 19:55
Okay, I guessed it. 'rspec' is another gem I needed to install.

**Comment by maximkhatskevich** [comment] 2017-03-14 19:57
MaxBook:MKHRequirement maxim$ xcake make
  - Reading Cakefile
  - Creating Project
  - Creating Target<MKHRequirement>
  - Resolving Project
  - Resolving Target<MKHRequirement>
  - Creating build configurations for Project<Main>
  - Creating build configuration Debug for Project<Main>
  - Creating build configuration Release for Project<Main>
  - Creating build configurations for Target<MKHRequirement>
  - Creating build configuration Debug for Target<MKHRequirement>
  - Creating build configuration Release for Target<MKHRequirement>
  - Integrating System Frameworks ["Foundation", "UIKit"] for
  Target<MKHRequirement>
  - Creating build phases for Target<MKHRequirement>
  - Creating User Schemes
/Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/scheme_generator.rb:33:in `block in visit_target': undefined method `build_for_running' for #<Xcodeproj::XCScheme::BuildAction:0x007fd6c2838cb8> (NoMethodError)
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/scheme_generator.rb:16:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/scheme_generator.rb:16:in `visit_target'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/visitor.rb:45:in `visit'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:82:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:82:in `accept'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:25:in `block in run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:23:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:23:in `run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/bin/xcake:6:in `<top (required)>'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/xcake:22:in `load'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/xcake:22:in `<main>'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'


Any ideas now?

**Comment by jcampbell05** [comment] 2017-03-14 19:57
:) yup, you're getting it - okay seems like this is a different error. Let me look through my code and see if I cab bash out a quick fix for you :) should be a simple one

**Comment by maximkhatskevich** [comment] 2017-03-14 19:58
would be awesome! Thx!

**Comment by jcampbell05** [comment] 2017-03-14 20:04
@maximkhatskevich so pushed a fix to `master`, I am writing some unit tests for it but feel free to pull it down and test it out :)

**Comment by maximkhatskevich** [comment] 2017-03-14 20:06
no, sorry, seems to be the same result :(

**Comment by maximkhatskevich** [comment] 2017-03-14 20:07
MaxBook:MKHRequirement maxim$ xcake make
  - Reading Cakefile
  - Creating Project
  - Creating Target<MKHRequirement>
  - Resolving Project
  - Resolving Target<MKHRequirement>
  - Creating build configurations for Project<Main>
  - Creating build configuration Debug for Project<Main>
  - Creating build configuration Release for Project<Main>
  - Creating build configurations for Target<MKHRequirement>
  - Creating build configuration Debug for Target<MKHRequirement>
  - Creating build configuration Release for Target<MKHRequirement>
  - Integrating System Frameworks ["Foundation", "UIKit"] for
  Target<MKHRequirement>
  - Creating build phases for Target<MKHRequirement>
  - Creating User Schemes
/Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/scheme_generator.rb:33:in `block in visit_target': undefined method `build_for_running' for #<Xcodeproj::XCScheme::BuildAction:0x007fdd96138f00> (NoMethodError)
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/scheme_generator.rb:16:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/scheme_generator.rb:16:in `visit_target'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/visitor.rb:45:in `visit'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:82:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:82:in `accept'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:25:in `block in run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:23:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:23:in `run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/bin/xcake:6:in `<top (required)>'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/xcake:22:in `load'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/xcake:22:in `<main>'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jcampbell05** [comment] 2017-03-14 20:10
@maximkhatskevich just so I can test this on my end is this the Cakemania Framework Example ?

**Comment by maximkhatskevich** [comment] 2017-03-14 20:12
no, it's one of my side projects. Let me try it with Cakemania, actually

**Comment by maximkhatskevich** [comment] 2017-03-14 20:13
Yes, same happens when I'm trying to run 'xcake make' against the Cakefile of framework example

**Comment by maximkhatskevich** [comment] 2017-03-14 20:14
Please, confirm if you see this crash on your side?

**Comment by jcampbell05** [comment] 2017-03-14 20:14
@maximkhatskevich cool, I'll use that to verify my fix rather than wasting your time :)

**Comment by maximkhatskevich** [comment] 2017-03-14 20:14
thx, I'm here waiting for the fix, really need this to move forward :)

**Comment by jcampbell05** [comment] 2017-03-14 20:23
@maximkhatskevich Cool, so I've tried fixing it. Turns out it was a minr feature to make xcake behave more like xcode. But I'll disable it for now :) and push it up.

**Comment by jcampbell05** [comment] 2017-03-14 20:23
Pushed :)

**Comment by maximkhatskevich** [comment] 2017-03-14 20:27
Okay, now it does not crash. I'm going to verify how it works in more details. Will let you know if I find any issues, of course.

**Comment by jcampbell05** [comment] 2017-03-14 20:28
@maximkhatskevich :) sure, need to get all these bugs out.

**Comment by maximkhatskevich** [comment] 2017-03-14 20:31
problems again

**Comment by maximkhatskevich** [comment] 2017-03-14 20:32
I uncommented my unit tests target in the Cakefile and getting this:


MaxBook:MKHRequirement maxim$ xcake make
  - Reading Cakefile
  - Creating Project
  - Creating Target<>
  - Creating Target<Tst>
  - Creating Target<MKHRequirement>
/Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/xcode/project.rb:118:in `file_reference_for_path': undefined method `dirname' for #<Xcodeproj::Project::Object::PBXFileReference:0x007f89c590d340> (NoMethodError)
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/context/xcodeproj_context.rb:56:in `file_reference_for_path'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/target_file_reference_generator.rb:33:in `include_file_for_path_and_target'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/target_file_reference_generator.rb:26:in `block in visit_target'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/target_file_reference_generator.rb:25:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/generator/target_file_reference_generator.rb:25:in `visit_target'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/visitor.rb:45:in `visit'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:82:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/dsl/project.rb:82:in `accept'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:25:in `block in run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:23:in `each'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/lib/xcake/command/make.rb:23:in `run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/gems/xcake-0.8.9/bin/xcake:6:in `<top (required)>'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/xcake:22:in `load'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/xcake:22:in `<main>'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/maxim/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'

**Comment by maximkhatskevich** [comment] 2017-03-14 20:32
What a big pain that Xcode project file!

**Comment by jcampbell05** [comment] 2017-03-14 20:33
@maximkhatskevich it's good, it's battle testing it :) I'll have a look into this :)

**Comment by maximkhatskevich** [comment] 2017-03-14 20:33
Maybe you require a specific version of Xcodeproj?

**Comment by jcampbell05** [comment] 2017-03-14 20:34
@maximkhatskevich I've been thinking about bumping up the requiremnt I think the one in the gemspec right now is too low we should limit support to the latest version since most people use the latest xcode :)

**Comment by maximkhatskevich** [comment] 2017-03-14 20:34
sure, I agree

**Comment by maximkhatskevich** [comment] 2017-03-14 20:35
Waiting for your updates/instructions :)

**Comment by jcampbell05** [comment] 2017-03-14 20:36
Do you know what xcodeproj you have btw ? will be interested to see where  `dirname` went

**Comment by maximkhatskevich** [comment] 2017-03-14 20:36
xcodeproj --version
1.4.2

**Comment by maximkhatskevich** [comment] 2017-03-14 20:37
Something you expected?

**Comment by jcampbell05** [comment] 2017-03-14 20:41
@maximkhatskevich looks like there is some file path I didn't code Xcake to support or something in Xcodeproj has changed and its now returning a file reference when Xcake didn't expect.

So Xcake is doing something unsupported and crashing. Just would like to know what that file path is. I'll probably need an example project for this one that can recreate the crash since it depends on what files you are trying to include etc :)

**Comment by maximkhatskevich** [comment] 2017-03-14 20:43
okay, give me a moment

**Comment by maximkhatskevich** [comment] 2017-03-14 20:47
Checkout project from 'develop' https://github.com/maximkhatskevich/MKHRequirement/tree/develop

**Comment by maximkhatskevich** [comment] 2017-03-14 20:47
The Cakefile is there

**Comment by maximkhatskevich** [comment] 2017-03-14 20:48
I was experimenting with Struct, btw, it is a bit more stable, but functionality is more limited than Xcake, so I'm getting back on Xcake, if will be able to make it work again for me :)

**Comment by lyptt** [comment] 2017-03-14 20:52
@maximkhatskevich Please feel free to file any issues on missing functionality in struct. It'd be great to add anything you're currently missing!

**Comment by jcampbell05** [comment] 2017-03-14 20:58
@maximkhatskevich Yeah I've decided Struct will be the better tool in the long term, so I'm helping to make that better and add what I can from Xcake. 

Of course not everything will make it as Struct is supposed to be tighter than Xcake.  'm hoping to get all of these bugs fixed in Xcake so I can have it in a good state as I know a lot of people like Xcake.

But like @lyptt says file what you are missing and I can help get it into Struct as well :)

**Comment by maximkhatskevich** [comment] 2017-03-14 20:58
@lyptt I'll take an eye on both projects, but currently the biggest thing is how unstable all that. So much unexpected/undocumented behavior, and I can't easy reuse settings in config file. @lyptt take a look on https://github.com/maximkhatskevich/MKHRequirement/blob/develop/Cakefile and notice how easy and naturally things are nested one into another and how nested scopes easy override what's been defined in an outer scope. For example, I define settings for all Build Configurations, and then override just one or two only for 'Release' configuration, etc. This is missing in Struct. The custom 'def ...' declarations not working - I made them work not causing crashes somehow, but overrides from then are not taking effect on the final project file. Or if I defined settings for all configurations, I can't add few specific overrides just for one Configuration.

**Comment by jcampbell05** [comment] 2017-03-14 20:59
@maximkhatskevich also checking out your project and will try it out :) sorry about this. I've decided to add some tests to see if Xcake can generate the Cakemania proects :)

https://github.com/maximkhatskevich/MKHRequirement/tree/develop

**Comment by maximkhatskevich** [comment] 2017-03-14 21:01
@lyptt @jcampbell05 but I do like how naturally Struct handles build schemes. It creates 1 sheme per target, which combines both Debug and Release build configurations as Xcode does by default (Debug for Run and Test, Release for Archive, etc., all inside the same cheme named after its target).

Also, project variants might be a better solution than having multiple custom Build Configurations and Shemes.

**Comment by jcampbell05** [comment] 2017-03-14 21:02
> @lyptt @jcampbell05 but I do like how naturally Struct handles build schemes. It creates 1 sheme per target, which combines both Debug and Release build configurations as Xcode does by default (Debug for Run and Test, Release for Archive, etc., all inside the same cheme named after its target).
> 
> Also, project variants might be a better solution than having multiple custom Build Configurations and Shemes.

I think we could look into getting some sort of high-level system or simplify variants to work in  a way with less of a learning curve if you  are more in the Xcode mindset :)  Xcake takes most of it's cues from Xcode which is why is has the nestling but it obviously adds alot of complexity when it had come to testing.

**Comment by lyptt** [comment] 2017-03-14 21:03
@maximkhatskevich So from this, I can see two main issues you're running into:
- Undocumented / unexplaned behaviour: Yes definitely we need more documentation. I'm 100% in support of this, the more documentation the better! I'll add an issue to track this.
- Reusing build configurations - yes I agree this can definitely be improved. Currently there's a bit of duplication when manually specifying configurations. I'll add an issue to investigate how we can go about this in a natural way.

**Comment by jcampbell05** [comment] 2017-03-14 21:03
@maximkhatskevich you should join the Gitter channel for Struct we can discuss this more :)

**Comment by maximkhatskevich** [comment] 2017-03-14 21:07
wow, what is Gitter? :)

**Comment by maximkhatskevich** [comment] 2017-03-14 21:08
@lyptt check the Specfile here https://github.com/maximkhatskevich/MKHRequirement/tree/develop you can see where I stopped trying to make it work :)

**Comment by jcampbell05** [comment] 2017-03-14 21:08
@maximkhatskevich It's a chat/IRC program that lets you chat to people based on the github repo :) so we can talk about Xcake just by going to the same url as this repo on gitter :)

**Comment by maximkhatskevich** [comment] 2017-03-14 21:14
@lyptt Struct is using Xcodeproj by CocoaPods under the hood as well?

**Comment by lyptt** [comment] 2017-03-14 21:15
@maximkhatskevich It is indeed! It's great having very active users like you, so I'd love to help make your use of struct as streamlined as possible. Please feel free to file issues on the struct repo and we can help smooth out the process of integrating with struct 👍

**Comment by maximkhatskevich** [comment] 2017-03-14 21:19
@lyptt okay I'll file the key issues I have, but basically I will be able to move on Struct if you make the Specfile work in the repo I gave earlier.

**Comment by jcampbell05** [comment] 2017-03-14 21:20
@lyptt It will be great to work together as well :) not many people seem to want to work on Xcode Project Generation. Can't say I can blame them when you get into it :P

**Comment by lyptt** [comment] 2017-03-14 21:22
@jcampbell05 Oh yeah tell me about it! Xcode is an absolute nightmare - and that's before you start working with it at such a low level 😂 Makes me wonder why I was insane enough to do it, but I can't help myself now!

**Comment by maximkhatskevich** [comment] 2017-03-14 21:24
@lyptt @jcampbell05 I'm wondering if Swift Package Manager can help us with project generation? IBM with their Kitura framework somehow generate project files as well, can you look into this? Probably we can learn something from there?

**Comment by lyptt** [comment] 2017-03-14 21:27
@maximkhatskevich I think most of our issues are centred around our 'approach' to generating projects. With Xcode projects there's a monumental amount of feature bloat, and factoring that down into something sensible is the hardest task!

The goal for struct was to boil down all these Xcode features and pick out the ones that developers use all the time, and make them incredibly simple to work with. This is basically the overall end-goal for the tool 🚀

**Comment by jcampbell05** [comment] 2017-03-14 21:40
@maximkhatskevich @lyptt I think in the long term SPM will become the project format for xcode, but not in a long time. Right now its super optimized for Swift frameworks like Kittura.

When I made Xcake, Cocoapods wasn't used by most developers. Fastlane and SPM didn't exist (Xcake was originally just a private tool that even used Sigh to download the certificates - @KrauseFx was onto something). It was supposed to in effect be a high-level Xcodeproj that allowed you to simply describe a project and allow you access to Xcode. This has ended up in some complexity as I've had to add things like watch app support and some Xcode Features are complex.

If I was building Xcake today :) I would probably build it more like Struct, since the times have changed. so its why I'm so excited to be working with someone as insane as me to be working with xcodeproject.

Someday I will write a talk about the project format it is crazy :)

**Comment by maximkhatskevich** [comment] 2017-03-14 21:47
To make a tool completely future-proof I would make it in Swift, but personally have no idea how to even approach this, as Xcode seems to not have (at least publicly documented) command-line API nor SDK. The only idea is to work with same Xcodeproj as you Xcake/Struct somehow, but it is made for work with from Ruby, have no idea how to communicate with it from Swift.

**Comment by lyptt** [comment] 2017-03-14 21:51
@maximkhatskevich Yeah, unfortunately there's no project parsers written in Swift, so it'd be a huge maintenance burden to move away from Xcodeproj. Also as Swift is a static language, it's going to be incredibly difficult to write a DSL for it, and it wouldn't be nearly as flexible as a Ruby DSL.

**Comment by jcampbell05** [comment] 2017-03-14 21:51
@maximkhatskevich yeah it's difficult since a lot of the Xcodeproject tooling is written in ruby right now thanks to the awesome people at Cocoapods :) I would love to do it in Swift but it would mean starting at a lower-level. 

You can usually call `xcake make` or `struct --generate` from most languages as most allow you to invoke system calls. And since Struct supports JSON, you can just spit that out / parse it in Swift :).

**Comment by maximkhatskevich** [comment] 2017-03-14 21:52
Agree with both of you.

**Comment by maximkhatskevich** [comment] 2017-03-14 21:54
@lyptt never seen an example of JSON version of the config. Do you have one? Does it allow string concatination for dynamic value composing from patterns? What about variables and reusing of code/settings?

**Comment by lyptt** [comment] 2017-03-14 21:58
Hi @maximkhatskevich, there aren't any JSON examples at present, but they act identically to the YAML variants. JSON is the most limited of the three formats, as YAML at least has the benefit of merge operators to copy keys and values into an object.

**Comment by lyptt** [comment] 2017-03-14 22:00
@maximkhatskevich An example of merge operators in YAML:

```yaml
.debug-config: &debug-config
  SWIFT_VERSION: '3.0'

targets:
  My app:
    configurations:
      debug:
        <<: *debug-config
```

**Comment by lyptt** [comment] 2017-03-14 22:02
@maximkhatskevich this results in the following JSON equivalent:

```json
{
  "targets": {
    "My app": {
      "configurations": {
        "debug": {
          "SWIFT_VERSION": "3.0"
        }
      }
    }
  }
}
```

**Comment by jcampbell05** [comment] 2017-03-14 22:06
We are talking about adding variables to JSON in future so maybe we could allow this:
```
{
"env: {
"debug-config": {
"SWIFT_VERSION": "3.0"
}
},
  "targets": {
    "My app": {
      "configurations": {
        "debug": "$debug-config"
      }
    }
  }
}
```

**Comment by maximkhatskevich** [comment] 2017-03-14 22:24
Okay, thanks for the example. If currently JSON is the most limited, then it's not helpful, agree. YAML seems to be the most elegant, as it is least verbose, I like it. But the lack of proper support of variables and string concatenation like in Ruby makes me use Ruby format for sure.

**Comment by maximkhatskevich** [comment] 2017-03-14 22:25
In near future, I would write a Swift wrapper around Struct that will then generate Specfile and execute 'struct -g'. Would be interesting to experiment with it.

**Comment by lyptt** [comment] 2017-03-14 22:29
@maximkhatskevich Yup! Struct was intended to also act as a middleman for other tooling, so this is absolutely supported. If you are comfortable with ruby, you can `require 'struct'` and use Struct's APIs directly to generate Specfiles dynamically.

**Comment by jcampbell05** [comment] 2017-03-15 08:31
Going to close this as the original crash was fixed and the one I'm fixing is this one https://github.com/jcampbell05/xcake/issues/154 so we can carry the conversation on their :)

**Closed by jcampbell05** 2017-03-15 08:31 UTC

**Comment by maximkhatskevich** [comment] 2017-03-16 22:53
@jcampbell05 @lyptt I hope you've got notifications about about this https://github.com/maximkhatskevich/MKHProjGen/issues/1
