### ISSUE TITLE
Xcake 0.8.8 crashes on reading Cakefile

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#143] opened 2017-02-23 16:21 UTC
Here is what I see in Terminal:

/Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/context/xcodeproj_context.rb:43:in `create_object_for_target': undefined method `new_target' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/context/xcodeproj_context.rb:17:in `create_object_for'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/context.rb:27:in `native_object_for'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/generator/default_project_structure_generator.rb:27:in `visit_target'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/visitor.rb:45:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `accept'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:25:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/bin/xcake:6:in `<top (required)>'
	from /usr/local/bin/xcake:23:in `load'
	from /usr/local/bin/xcake:23:in `<main>'

**Comment by jcampbell05** [comment] 2017-02-26 13:45
@maximkhatskevich Could you upload an example project for me to test against ?

**Comment by maximkhatskevich** [comment] 2017-02-26 14:24
@jcampbell05 for some reason it does not happen anymore. After the issue appeared, I rolled back to one of the previous versions, then installed latest version again and it started to work properly. Should be something related to the environment on my computer.

**Comment by jcampbell05** [comment] 2017-02-26 15:01
@maximkhatskevich  potentially could be the xcodeproj version

**Comment by maximkhatskevich** [comment] 2017-02-26 15:20
maybe, because I updated everything I could while was trying to resolve the issue

**Comment by jcampbell05** [comment] 2017-02-26 22:03
Let me know if you get it again, will be good to track the version effected :)

**Comment by frankdilo** [comment] 2017-03-01 10:01
Seeing the same problem on version `0.8.7`

**Comment by jcampbell05** [comment] 2017-03-01 19:34
@frankdilo are you able to tell me what version of xcodeproj you are using ?

**Comment by alaincaltieri** [comment] 2017-03-02 15:57
Hi!
I'm experiencing the same issue with Xcake 0.8.8. My version of xcodeproj is 1.4.2. Here the stacktrace, which is the same as @maximkhatskevich 

```
  - Reading Cakefile
  - Resolving Project
  - Resolving Target<Specs>
/Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/context/xcodeproj_context.rb:43:in `create_object_for_target': undefined method `new_target' for nil:NilClass (NoMethodError)
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/context/xcodeproj_context.rb:17:in `create_object_for'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/context.rb:27:in `native_object_for'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/default_project_structure_generator.rb:27:in `visit_target'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/visitor.rb:45:in `visit'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:83:in `block in accept'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `each'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `accept'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:25:in `block in run'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `each'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `run'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/gems/xcake-0.8.8/bin/xcake:6:in `<top (required)>'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/bin/xcake:23:in `load'
  from /Users/pv/bunker/shared/bundle/ruby/2.2.0/bin/xcake:23:in `<main>'
```

**Comment by jcampbell05** [comment] 2017-03-02 16:15
Interesting seems to be due to the resolving step, I'll try to recreate this. If anyone has a project and cakefile they can upload that will be a big help.

**Comment by alaincaltieri** [comment] 2017-03-02 16:39
Hi @jcampbell05 
I prepared a dummy Cakefile that replicates the issue. 

```
INSTANCE = 'Test'

project.name = 'Test'
project.organization = 'ORGANIZATION'

debug_configuration :Debug
release_configuration :Release

project.all_configurations.each do |configuration|
    configuration.settings["SWIFT_VERSION"] = "3.0"
end

target do |target|
    target.name = INSTANCE
    target.platform = :ios
    target.deployment_target = 9.3
    target.language = :swift
    target.type = :application
    target.include_files = [
        "MyApp/**/*.swift"
    ]

    
    target.all_configurations.each do |configuration|
        configuration.settings["ENABLE_BITCODE"] = "NO"

        configuration.settings["ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME"] = "LaunchImage"    
        configuration.settings["CODE_SIGN_IDENTITY[sdk=iphoneos*]"] = "iPhone Distribution"
	
    end

    unit_tests_for target do |unit_test|
        unit_test.linked_targets = [target]
        unit_test.name = "Specs"
        unit_test.include_files = [
            "MyTests/**/*.*",
        ]

        unit_test.all_configurations.each do |configuration|
            configuration.settings["INFOPLIST_FILE"] = "MyTests/Info.plist"
        end
    end

end
```

`xcake make` does not always fail. On my machine it happens once every 4-5 builds, so maybe you'll have to try a bunch of times to see the error. Also the above Cakefile works fine also without any other project file in the same folder :)

**Comment by maximkhatskevich** [comment] 2017-03-02 21:50
@jcampbell05 today I needed to regenerate project file and this issue happened again. 'xcode-select install' says I have latest tool installed. And again, the issue has been eliminated after I removed xcake at all, then installed earlier versions (I tried 0.8.7, 0.8.6, 0.8.3 - and they all were crashing). Then I removed xcake at all again and then just installed latest version available. And after that 'xcake make' worked well, no issues.

**Comment by jcampbell05** [comment] 2017-03-02 23:05
@maximkhatskevich So cleaning all Xcake versions to make sure you had 0.8.8 fixed it ?

**Comment by maximkhatskevich** [comment] 2017-03-02 23:12
@jcampbell05 it looks like this. But since I last time tried to fix this issue I think I only had v.0.8.8 installed anyway, so I'm not sure why it helps to switch to earlier version, then remove it and install latest version again.

**Comment by maximkhatskevich** [comment] 2017-03-02 23:16
Configurations defined like this:
https://github.com/jcampbell05/xcake/blob/master/example/app/CakeMania/Cakefile#L53

But even basic settings from this part (which should be applied to all Configurations that we have in the project)
https://github.com/jcampbell05/xcake/blob/master/example/app/CakeMania/Cakefile#L215
are not applied to configurations except "Debug" and "Release".

**Comment by maximkhatskevich** [comment] 2017-03-02 23:18
I'm not even sure when this issue was introduced, because I was only running my apps in Simulator from Xcode using "Debug" Build Configuration for the last few months. Now I tried to run my app on device using another Scheme with a custom Configuration ("RC") and realized I have big troubles with build settings.

**Comment by jcampbell05** [comment] 2017-03-02 23:30
@maximkhatskevich It's very interesting, If I can nail down where this is caused I would like to had some more integration tests and tests with the actual Cakefiles rather than just unit tests.

Seems what we have isn't enougth anymore as the tool as got more complex.

**Comment by maximkhatskevich** [comment] 2017-03-02 23:34
I can participate in testing, if you can give me development version and it's not too complex to install one on my computer. I have zero knowledge about how Ruby apps work and install, etc. :)

**Comment by jcampbell05** [comment] 2017-03-02 23:49
@maximkhatskevich So to test any development version of xcake all you need to do is clone the repo and just run `rake install` then the development version will be installed :)  I'll let you know when I have some changes.

**Comment by james-aiwip** [comment] 2017-03-11 23:39
So I've found a way of testing Xcake in a way that can reproduce this crash, simply by running xcake make, 10,000 times I am able to spot some steps change order which shouldn't be a problem as long as they don't depend on each other.

But a couple of times I have that crash but not as often as you guys seem to be getting it.

I will probably add this test into the Xcake test suite as part of the new functional tests I'm looking into adding but I am look into the underlying cause as well.

**Comment by james-aiwip** [comment] 2017-03-11 23:42
So I think I've located the problem that causes this crash, in a few cases the project is created later than expected which isn't ideal. This means that Xcake will try to create a target by calling the `new_target` method on `nil`.

This seems related to the fact some steps change order as noted above, so I'll look further into why these change.

**Comment by jcampbell05** [comment] 2017-03-11 23:52
So think I've located the issue causing this problem in #147, I simply needed to stop one of the new generators I introduced when adding support for schemes executing too early before xcake had created the project.

This caused the nil error since the project was nil. It now shouldn't execute until Xcake has finished processing the Target and Project.

**Closed** 2017-03-12 00:11 UTC
Labels: bug
